#!/bin/bash
device=/dev/sdb
home=/home/caixin
mountDir=${home}"/HDD_storage"
baseDir=${mountDir}"/bDB"


#echo 3 > /proc/sys/vm/drop_caches  #清缓存
#umount ${mountDir}
#mkfs.ext4 -F ${device}
#mount -t ext4  ${device}  ${mountDir}
#
#echo ....... branchDB-17_1_thread_test_read_5_100_--strictRO=1_--numMaxThreadsDoingGC=1 ..........
#
#../earth17_1/db_bench   --benchmarks=fillseq,stats,fillrandom,stats,readrandom,stats,readseq,stats --bloom_bits=10 --db=${baseDir}  --num=100000000 --reads=5000000 --open_files=10000  --value_size=1024 --compression_ratio=1 --histogram=1 --strictRO=1 --numMaxThreadsDoingGC=1


echo 3 > /proc/sys/vm/drop_caches  #清缓存
umount ${mountDir}
mkfs.ext4 -F ${device}
mount -t ext4  ${device}  ${mountDir}

echo ....... branchDB_4_thread_test_read_5_100 ..........

./db_bench --benchmarks=fillseq,stats,fillrandom,stats,readrandom,stats,readseq,stats --bloom_bits=10 --db=${baseDir}  --num=100000000 --reads=5000000 --open_files=10000  --value_size=1024 --compression_ratio=1 --histogram=1 >> BranchDB_testFull



echo 3 > /proc/sys/vm/drop_caches  #清缓存
umount ${mountDir}
mkfs.ext4 -F ${device}
mount -t ext4  ${device}  ${mountDir}

echo ....... branchDB_4_thread_test_read_5_100 ..........

./db_bench --benchmarks=fillseq,stats,fillrandom,stats,readrandom,stats,readseq,stats --bloom_bits=10 --db=${baseDir}  --num=100000000 --reads=5000000 --open_files=10000  --value_size=1024 --compression_ratio=1 --histogram=1 --fixLevelandSeqs=1 --maxAppendLevelIdx=1 --maxSequences=3 >> BranchDB_testFull



#echo 3 > /proc/sys/vm/drop_caches  #清缓存
#umount ${mountDir}
#mkfs.ext4 -F ${device}
#mount -t ext4  ${device}  ${mountDir}
#
#echo ....... branchDB-17_1_thread_test_read_5_100_--strictRO=1 ..........
#
#../earth17_1/db_bench   --benchmarks=fillseq,stats,fillrandom,stats,readrandom,stats,readseq,stats --bloom_bits=10 --db=${baseDir}  --num=100000000 --reads=5000000 --open_files=10000  --value_size=1024 --compression_ratio=1 --histogram=1 --strictRO=1
#
#
#
#
#echo 3 > /proc/sys/vm/drop_caches  #清缓存
#umount ${mountDir}
#mkfs.ext4 -F ${device}
#mount -t ext4  ${device}  ${mountDir}
#
#echo ....... branchDB-17_4_thread_test_read_5_100_--strictRO=1 ..........
#
#../earth17/db_bench   --benchmarks=fillseq,stats,fillrandom,stats,readrandom,stats,readseq,stats --bloom_bits=10 --db=${baseDir}  --num=100000000 --reads=5000000 --open_files=10000  --value_size=1024 --compression_ratio=1 --histogram=1 --strictRO=1 
#
#
#
#
#echo 3 > /proc/sys/vm/drop_caches  #清缓存
#umount ${mountDir}
#mkfs.ext4 -F ${device}
#mount -t ext4  ${device}  ${mountDir}
#
#echo ....... branchDB-17_1_thread_test_readseq_--strictRO=1_--numMaxThreadsDoingGC=1 ..........
#
#../earth17_1/db_bench   --benchmarks=fillrandom,stats,readseq,stats --bloom_bits=10 --db=${baseDir}  --num=100000000 --open_files=10000  --value_size=1024 --compression_ratio=1 --histogram=1 --strictRO=1 --numMaxThreadsDoingGC=1
#
#
#
#echo 3 > /proc/sys/vm/drop_caches  #清缓存
#umount ${mountDir}
#mkfs.ext4 -F ${device}
#mount -t ext4  ${device}  ${mountDir}
#
#echo ....... branchDB-17_4_thread_test_readseq_--strictRO=1_--numMaxThreadsDoingGC=1 ..........
#
#../earth17/db_bench   --benchmarks=fillrandom,stats,readseq,stats --bloom_bits=10 --db=${baseDir}  --num=100000000 --open_files=10000  --value_size=1024 --compression_ratio=1 --histogram=1 --strictRO=1 --numMaxThreadsDoingGC=1
#
#
#
#
#echo 3 > /proc/sys/vm/drop_caches  #清缓存
#umount ${mountDir}
#mkfs.ext4 -F ${device}
#mount -t ext4  ${device}  ${mountDir}
#
#echo ....... branchDB-17_1_thread_test_readseq_--strictRO=1 ..........
#
#../earth17_1/db_bench   --benchmarks=fillrandom,stats,readseq,stats --bloom_bits=10 --db=${baseDir}  --num=100000000 --open_files=10000  --value_size=1024 --compression_ratio=1 --histogram=1 --strictRO=1
#
#
#
#
#echo 3 > /proc/sys/vm/drop_caches  #清缓存
#umount ${mountDir}
#mkfs.ext4 -F ${device}
#mount -t ext4  ${device}  ${mountDir}
#
#echo ....... branchDB-17_4_thread_test_readseq_--strictRO=1 ..........
#
#../earth17/db_bench   --benchmarks=fillrandom,stats,readseq,stats --bloom_bits=10 --db=${baseDir}  --num=100000000 --open_files=10000  --value_size=1024 --compression_ratio=1 --histogram=1 --strictRO=1 
#



