g++ db_test.cc -o db_test -lpthread  -BRANCHDB_PLATFORM_POSIX -I ~/earth/include ~/earth/libbranchdb.a  -g  #-lsnappy 
g++ -o openExist -I ~/earth/include openExist.cc  ~/earth/libbranchdb.a -lpthread -BRANCHDB_PLATFORM_POSIX -g #-lsnappy 
#g++ db_bench.cc -o db_bench -lsnappy  -fno-builtin-memcmp -pthread -DOS_LINUX -DBRANCHDB_PLATFORM_POSIX -g2  -I ~/earth/include -I ~/earth/  ~/earth/libbranchdb.a 
    


